@startuml
!include ../constants.puml

class YlabPropertyEnumTable extends PropertyEnumTable
{
    !startsub METHODS
    !includesub ROOT/main/DataManager.puml!METHODS
    !includesub ROOT/iblock/PropertyEnumTable.puml!METHODS
    !endsub
}

@enduml