@startuml
!include ../constants.puml

class YlabIblockTable extends IblockTable
{
    !startsub METHODS
    !includesub ROOT/main/DataManager.puml!METHODS
    !includesub ROOT/iblock/IblockTable.puml!METHODS
    !endsub
}

@enduml