@startuml
!include ../../constants.puml

class ElementPropertyTableRelationMapper extends RelationMapper
{
    !startsub METHODS
    !includesub ROOT/factory/relation/ElementTableRelationMapper.puml!METHODS
    !endsub
}

@enduml